name: FFmpeg Linux Build

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]
    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ matrix.platform }} release
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          file: Dockerfile
          load: true
          tags: ffmpeg:latest

      - name: Copy files
        run: |
          container_id=$(docker create ffmpeg:latest)
          docker cp $container_id:/app/dest .
          docker rm -v $container_id

      - name: Create GH release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: true
          files: |
            ./dest/*.tar.xz

  macos:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [macos-13, macos-14]
    steps:
      - uses: actions/checkout@v3

      - name: Build macOS release
        run: |
          ./build.sh

      - name: Create GH release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: true
          files: |
            ./dest/*.tar.xz